INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '3');


INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN1', 'Công nghệ thông tin');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN2', 'Kĩ thuật máy tính');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN3', 'Vật lý kĩ thuật');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN4', 'Cơ kĩ thuật');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN5', 'Công nghệ kĩ thuật xây dựng');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN6', 'Công nghệ kĩ thuật cơ điện tử');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN7', 'Công nghệ hàng không vũ trụ');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN8', 'Khoa học máy tính');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN9', 'Công nghệ kĩ thuật Điện tử - Viễn thông');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN10', 'Công nghệ nông nghiệp');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN11', ' Kỹ thuật điều khiển và tự động hoá');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN12', 'Trí tuệ nhân tạo');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN13', 'Kỹ thuật năng lượng');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN14', 'Hệ thống thông tin');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN15', 'Mạng máy tính và truyền thông dữ liệu');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN16', 'CNTT định hướng thị trường Nhật Bản');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN17', 'Kỹ thuật Robot');


INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1008', '4', 'Nhập môn lập trình');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1007', '3', 'GTCNTT');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2215', '4', 'Lập trình nâng cao');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2204', '4', 'Lập trình hướng đối tượng');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PHI1006', '3', 'Triết học Mác - Lênin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PEC1008', '2', 'Kinh tế chính trị Mác - Lênin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('FLF1107', '5', 'Tiếng anh B1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('FLF1108', '5', 'Tiếng anh B2');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PHI1002', '2', 'Chủ nghĩa xã hội khoa học');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('HIS1001', '2', 'Lịch sử Đảng');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('POL1001', '2', 'Tư tưởng Hồ Chí Minh');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1093', '4', 'Đại số');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('EPN1095', '2', 'Vật lý đại cương 1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('EPN1096', '2', 'Vật lý đại cương 2');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1041', '4', 'Giải tích 1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2210', '4', 'Cấu trúc dữ liệu và giải thuật');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('ELT2035', '3', 'Tín hiệu hệ thống');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('ELT2029', '3', 'Toán trong công nghệ');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1101', '3', 'Xác suất thống kê');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3416', '3', 'Lập trình thuật toán');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3123', '3', 'Các thuật toán đồ thị và ứng dung');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3405', '3', 'Học máy');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3105', '3', 'Kiến trúc phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3213', '3', 'Nhập môn an toàn thông tin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3415', '3', 'Phát triển ứng dụng di động nâng cao');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3111', '3', 'Quản lý dự án phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3135', '3', 'Tính toán di động');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2211', '4', 'Cơ sở dữ liệu');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2212', '4', 'Kiến trúc máy tính');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1050', '4', 'Toán rời rạc');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2208', '3', 'Công nghệ phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2213', '4', 'Mạng máy tính');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2214', '4', 'Nguyên lý hệ điều hành');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3401', '3', 'Trí tuệ nhân tạo');



INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '68');



INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('1', 'lnlrjcthez', '2004-12-01', '3');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('2', 'xkpthvmttq', '2004-12-16', '8');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('3', 'jfbpyvvrho', '2005-01-20', '26');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('4', 'pszdkkaptv', '2004-11-19', '1');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('5', 'gkrqxuydsd', '2004-12-21', '13');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('6', 'suewfyaubd', '2004-11-28', '10');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('7', 'appcviufxd', '2004-12-11', '3');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('8', 'isdsmjxwma', '2004-12-17', '9');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('9', 'mkzqjxmoxa', '2004-12-24', '16');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('10', 'gsmthswqre', '2005-01-30', '16');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('11', 'kycopbdrug', '2004-11-26', '8');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('12', 'knvorygati', '2004-12-07', '9');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('13', 'hjwlsioddo', '2005-01-06', '12');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('14', 'womrvkjads', '2005-01-07', '13');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('15', 'sxxikhmmvn', '2004-12-20', '12');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('16', 'ghxfjcxwll', '2005-01-27', '13');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('17', 'vpmlzrchtj', '2004-12-23', '15');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('18', 'lbzikqplne', '2005-02-12', '29');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('19', 'mpsjzmsqnx', '2005-01-10', '16');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('20', 'qzahwhkeiw', '2005-02-01', '18');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('21', 'ailvtjycwb', '2004-12-31', '6');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('22', 'epiviyoyth', '2005-01-19', '25');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('23', 'wjidrwgdej', '2004-12-28', '3');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('24', 'nsbduaoqpn', '2004-12-06', '8');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('25', 'jpxxxkftba', '2005-02-07', '24');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('26', 'npyjweisem', '2005-01-05', '11');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('27', 'jignmhffps', '2004-12-13', '5');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('28', 'cbaaxjwzuj', '2004-11-25', '7');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('29', 'twpmlmubuo', '2004-12-25', '17');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('30', 'nreiecvatr', '2004-12-18', '10');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('31', 'ysixfmvubm', '2004-12-08', '10');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('32', 'yrmvozhetp', '2005-01-03', '9');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('33', 'gaapbvwqjr', '2004-11-23', '5');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('34', 'soqpbbjpyk', '2005-01-02', '8');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('35', 'fmvrzaajmx', '2004-11-22', '4');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('36', 'fuysiwgyit', '2004-12-14', '6');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('37', 'vifvotwneo', '2005-01-11', '17');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('38', 'tmbwzlvzve', '2005-02-05', '22');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('39', 'bxukfntjhw', '2004-12-02', '4');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('40', 'tqfpodykez', '2005-02-13', '30');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('41', 'jitgttjnim', '2004-12-03', '5');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('42', 'ajrpqiehzv', '2004-12-19', '11');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('43', 'vwkxhffuqk', '2005-01-29', '15');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('44', 'witmacovix', '2005-01-31', '17');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('45', 'fnlekopjvy', '2005-01-22', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('46', 'qqqjxaiksv', '2005-02-02', '19');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('47', 'qtyecwgswx', '2005-01-24', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('48', 'cnepquacov', '2005-01-16', '22');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('49', 'rafpvssapf', '2005-02-09', '26');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('50', 'uqllcjdcsc', '2005-02-08', '25');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('51', 'msiibhyqnp', '2005-01-01', '7');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('52', 'pqbagssywz', '2004-11-24', '6');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('53', 'allmxqfxkm', '2005-01-09', '15');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('54', 'amanknmevq', '2005-02-10', '27');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('55', 'yrqkrqbfvf', '2005-01-23', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('56', 'zcgerbxngc', '2005-02-04', '21');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('57', 'xlgsdxsdca', '2004-11-29', '1');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('58', 'anpprajmww', '2004-12-30', '5');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('59', 'oxtnqjdcnh', '2005-01-15', '21');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('60', 'ovnqtiaaak', '2004-12-26', '1');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('61', 'opufjfbuei', '2005-01-17', '23');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('62', 'tudiwyfkag', '2004-11-27', '9');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('63', 'qlirbqwtsm', '2004-12-12', '4');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('64', 'rstsbqorxz', '2004-12-27', '2');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('65', 'zklunqrfql', '2005-02-06', '23');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('66', 'wdphbswwoe', '2004-11-21', '3');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('67', 'mucckuiwlb', '2005-01-18', '24');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('68', 'denqhswrog', '2005-01-26', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('69', 'nehbouamrq', '2004-11-20', '2');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('70', 'oyzjurvxeh', '2005-01-08', '14');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('71', 'ukrxjmpwbx', '2005-01-14', '20');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('72', 'ihdbnitfsy', '2005-01-21', '27');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('73', 'bnkqsogtna', '2005-01-04', '10');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('74', 'lmxugmsekp', '2004-11-30', '2');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('75', 'gdufrkslwf', '2005-01-28', '14');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('76', 'zjpmqusdch', '2005-02-11', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('77', 'bzefuccawh', '2005-01-13', '19');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('78', 'mfqkwewptf', '2004-12-09', '1');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('79', 'sgthpdjnrf', '2005-01-12', '18');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('80', 'jpohrdemxb', '2004-12-05', '7');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('81', 'zacwudwegg', '2005-01-25', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('82', 'ysbpjdgiaq', '2005-02-03', '20');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('83', 'ulrwwfxmhu', '2004-12-22', '14');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('84', 'cmahikgysq', '2004-12-04', '6');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('85', 'ftezmouakv', '2004-12-10', '2');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('86', 'hvsixntqed', '2004-12-29', '4');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('87', 'irulcjdshm', '2004-12-15', '7');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('88', 'wirgeudlod', '2004-12-16', '8');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('89', 'jsqnwhvtfk', '2004-12-17', '9');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('90', 'tajymwncsr', '2004-12-18', '10');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('91', 'addqwvjbrt', '2004-12-19', '11');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('92', 'rxekqscfoo', '2004-12-20', '12');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('93', 'dxrfuxozhr', '2004-12-21', '13');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('94', 'xhofrytgsu', '2004-12-22', '14');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('95', 'kwsusdponi', '2004-12-23', '15');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('96', 'kjxwlxxbdk', '2004-12-24', '16');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('97', 'mhxysutpoi', '2004-12-25', '17');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('98', 'xopxhsegug', '2004-12-26', '18');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('99', 'wwzpeijnlb', '2004-12-27', '19');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('100', 'euehyvnupd', '2004-12-28', '20');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('101', 'usjylxevfz', '2004-12-29', '21');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('102', 'xcxdoghthl', '2004-12-30', '22');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('103', 'nvmnfncijg', '2004-12-31', '23');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('104', 'jiixvpntlb', '2005-01-01', '24');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('105', 'vinwaaymln', '2005-01-02', '25');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('106', 'edzzffqyzw', '2005-01-03', '26');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('107', 'khjugyptql', '2005-01-04', '27');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('108', 'tkahqvwbvu', '2005-01-05', '28');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('109', 'peladapotz', '2005-01-06', '29');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('110', 'eqrcydqvxi', '2005-01-07', '30');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('111', 'ultwosgppe', '2005-01-08', '31');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('112', 'mozlvaoced', '2005-01-09', '32');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('113', 'wqulnwltdn', '2005-01-10', '33');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('114', 'mlogowadqt', '2005-01-11', '34');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('115', 'mhnonqtoue', '2005-01-12', '35');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('116', 'rxhjbjmlaj', '2005-01-13', '36');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('117', 'deetbgjubx', '2005-01-14', '37');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('118', 'ujwcijqqzy', '2005-01-15', '38');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('119', 'dlcevoqqrq', '2005-01-16', '39');
INSERT INTO `projectdb_quanlidaotao`.`student` (`id`, `name`, `date_of_birth`, `course_class_id`) VALUES ('120', 'vqtblnajxb', '2005-01-17', '40');


INSERT INTO `projectdb_quanlidaotao`.`subjectclass` (`subject_id`, `semester_id`, `class_index`, `room`, `start_time`, `end_time`, `week_day`) VALUES ('1', '3', '20', '301-G2', '8:00', '9:00', 'mon');
INSERT INTO `projectdb_quanlidaotao`.`subjectclass` (`subject_id`, `semester_id`, `class_index`, `room`, `start_time`, `end_time`, `week_day`) VALUES ('1', '2', '21', '107-G2', '9:00', '11:00', 'mon');
INSERT INTO `projectdb_quanlidaotao`.`subjectclass` (`subject_id`, `semester_id`, `class_index`, `room`, `start_time`, `end_time`, `week_day`) VALUES ('2', '2', '40', '106-G2', '7:00', '10:00', 'tue');


INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('1', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('1', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('1', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('2', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('2', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('2', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('3', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('3', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('3', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('4', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('4', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('4', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('5', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('5', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('5', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('6', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('6', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('6', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('7', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('7', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('7', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('8', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('8', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('8', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('9', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('9', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('9', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('10', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('10', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('10', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('11', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('11', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('11', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('12', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('12', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('12', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('13', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('13', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('13', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('14', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('14', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('14', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('15', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('15', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('15', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('16', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('16', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('16', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('17', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('17', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('17', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('18', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('18', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('18', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('19', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('19', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('19', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('20', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('20', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('20', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('21', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('21', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('21', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('22', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('22', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('22', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('23', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('23', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('23', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('24', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('24', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('24', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('25', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('25', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('25', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('26', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('26', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('26', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('27', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('27', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('27', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('28', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('28', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('28', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('29', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('29', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('29', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('30', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('30', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('30', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('31', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('31', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('31', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('32', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('32', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('32', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('33', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('33', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('33', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('34', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('34', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('34', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('35', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('35', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('35', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('36', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('36', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('36', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('37', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('37', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('37', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('38', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('38', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('38', '3');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('39', '1');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('39', '2');
INSERT INTO `projectdb_quanlidaotao`.`takeclass` (`student_id`, `subject_class_id`) VALUES ('39', '3');

