INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2019', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2020', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2021', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2022', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2023', '3');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '1');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '2');
INSERT INTO `projectdb_quanlidaotao`.`semester` (`year_start`, `term`) VALUES ('2024', '3');


INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN1', 'Công nghệ thông tin');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN2', 'Kĩ thuật máy tính');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN3', 'Vật lý kĩ thuật');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN4', 'Cơ kĩ thuật');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN5', 'Công nghệ kĩ thuật xây dựng');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN6', 'Công nghệ kĩ thuật cơ điện tử');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN7', 'Công nghệ hàng không vũ trụ');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN8', 'Khoa học máy tính');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN9', 'Công nghệ kĩ thuật Điện tử - Viễn thông');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN10', 'Công nghệ nông nghiệp');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN11', ' Kỹ thuật điều khiển và tự động hoá');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN12', 'Trí tuệ nhân tạo');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN13', 'Kỹ thuật năng lượng');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN14', 'Hệ thống thông tin');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN15', 'Mạng máy tính và truyền thông dữ liệu');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN16', 'CNTT định hướng thị trường Nhật Bản');
INSERT INTO `projectdb_quanlidaotao`.`major` (`code`, `name`) VALUES ('CN17', 'Kỹ thuật Robot');


INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1008', '4', 'Nhập môn lập trình');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1007', '3', 'GTCNTT');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2215', '4', 'Lập trình nâng cao');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2204', '4', 'Lập trình hướng đối tượng');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PHI1006', '3', 'Triết học Mác - Lênin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PEC1008', '2', 'Kinh tế chính trị Mác - Lênin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('FLF1107', '5', 'Tiếng anh B1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('FLF1108', '5', 'Tiếng anh B2');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('PHI1002', '2', 'Chủ nghĩa xã hội khoa học');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('HIS1001', '2', 'Lịch sử Đảng');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('POL1001', '2', 'Tư tưởng Hồ Chí Minh');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1093', '4', 'Đại số');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('EPN1095', '2', 'Vật lý đại cương 1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('EPN1096', '2', 'Vật lý đại cương 2');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1041', '4', 'Giải tích 1');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2210', '4', 'Cấu trúc dữ liệu và giải thuật');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('ELT2035', '3', 'Tín hiệu hệ thống');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('ELT2029', '3', 'Toán trong công nghệ');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('MAT1101', '3', 'Xác suất thống kê');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3416', '3', 'Lập trình thuật toán');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3123', '3', 'Các thuật toán đồ thị và ứng dung');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3405', '3', 'Học máy');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3105', '3', 'Kiến trúc phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3213', '3', 'Nhập môn an toàn thông tin');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3415', '3', 'Phát triển ứng dụng di động nâng cao');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3111', '3', 'Quản lý dự án phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3135', '3', 'Tính toán di động');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2211', '4', 'Cơ sở dữ liệu');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2212', '4', 'Kiến trúc máy tính');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT1050', '4', 'Toán rời rạc');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2208', '3', 'Công nghệ phần mềm');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2213', '4', 'Mạng máy tính');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT2214', '4', 'Nguyên lý hệ điều hành');
INSERT INTO `projectdb_quanlidaotao`.`subject` (`subject_code`, `credit`, `subject_name`) VALUES ('INT3401', '3', 'Trí tuệ nhân tạo');



INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('1', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('2', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('3', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('4', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('5', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('6', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('7', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('8', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('9', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('10', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('11', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('12', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('13', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('14', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('15', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('16', '68');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '64');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '65');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '66');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '67');
INSERT INTO `projectdb_quanlidaotao`.`courseclass` (`major_id`, `gen`) VALUES ('17', '68');

